name: playwright

on:
  - push

jobs:
  playwright:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        browser:
          - chrome
          - firefox
          - msedge
          - webkit
        # fail combinations
        exclude:
          - os: ubuntu-latest
            browser: msedge
          - os: ubuntu-latest
            browser: webkit
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.browser }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.browser }}-yarn-
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: npx playwright install ${{ matrix.browser }}
        if: matrix.browser == 'firefox' || matrix.browser == 'webkit'
      - run: npx playwright test --project=${{ matrix.browser }}
      - run: mv example.png example-${{ runner.os }}-${{ matrix.browser }}.png
      - uses: actions/upload-artifact@v3
        with:
          path: example-${{ runner.os }}-${{ matrix.browser }}.png
